---
resources:
  - name: config
    type: git
    source:
      uri: https://github.com/hreeder/concourse-config

jobs:
  - name: configure
    plan:
      - get: config
        trigger: true
      - task: configure
        file: config/ci/tasks/configure.yml
        vars:
          concourse_url: https://ccrs.err.wtf/
          concourse_username: ((concourse.username))
          concourse_password: ((concourse.password))
