---
resource_types:
  - name: discord
    type: docker-image
    source:
      repository: trivigy/discord-resource

resources:
  - name: config
    type: git
    source:
      uri: https://github.com/hreeder/concourse-config
  - name: discord
    type: discord
    check_every: 999999h
    source:
        token: ((discord.token))

jobs:
  - name: configure
    plan:
      - get: config
        trigger: true
      - task: configure
        file: config/ci/tasks/configure.yml
        vars:
          concourse_url: https://ci.tbrb.dev/
          concourse_username: ((concourse.username))
          concourse_password: ((concourse.password))
      - put: discord
        params:
          channel: "((discord.channel_id))"
          color: 0x5CB85C
          title: "[Concourse] Job Has Completed"
          message: |
            **Pipeline**: concourse-config
            **Job**: configure
            :airplane_departure: Concourse has now been configured successfully.
